# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37b76c4e2204ab63557594eca351d2649995eac572536767acd25770a4faf85c1b06ebf9c547f16a2899cc62246a299fa5959a36afd00b4f0a96c11013364d6c

test:
  secret_key_base: 0bf095e663ed7a51558cc5e1819f77a8749abe182c1b84d3980a37bb7e67440e22b8d6d0d4c15fc76ac1d02bb3235e1418640dd0d3469f066de49abe68906d16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
